### PR TITLE
Add support for IntelliJ 2020.*

### LINKED ISSUE #16: Feature request: Suport for 2020.x series of IDES

### PR DESCRIPTION
**Pull request by camsteffen**
Fixes #16

### CODE REVIEW

**Comment by Vincent-P** [comment]
Thanks a lot for your PR!

**Comment by astrolemonade** [comment]
When will it be released in the marketplace?

**Comment by Vincent-P** [comment]
When Jetbrains is done reviewing the update, so in a few days probably.

**Comment by astrolemonade** [comment]
Thank you

**Pull request merged**
